name: "test #allure-pytest/636"

on: workflow_dispatch

jobs:
  test:
    name: Test reproduction of issue 636
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    env:
      ALLURE_INDENT_OUTPUT: "true"
    steps:
      - uses: actions/checkout@v3

      - name: Enable python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Install packages"
        run: python -m pip install -U pip setuptools wheel &&
             pip install pytest pytest-bdd allure-pytest-bdd

      - name: "Run pytest-bdd with allure"
        run: pytest -m cucumber -W ignore --alluredir allure-results

      - name: Show result files
        run: cat ./allure-results/*-result.json
